image: registry.gitlab.com/radoslav-stefanov/dind-container/master:latest

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

stages:
  - Build
  - Tag

before_script:
  - export PROJECT_PATH=registry.gitlab.com/radoslav-stefanov/pimpmylogs
  - export GIT_SHORT_COMMIT_SHA=${CI_COMMIT_SHA:0:7}
  - export IMAGE_NAME=$PROJECT_PATH/$CI_COMMIT_REF_SLUG:$GIT_SHORT_COMMIT_SHA
  - export RELEASE_IMAGE_NAME=$PROJECT_PATH/$CI_COMMIT_REF_SLUG:latest


build:
  stage: Build
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - echo built and pushed image $IMAGE_NAME

tag:
  stage: Tag
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $IMAGE_NAME
    - docker tag $IMAGE_NAME $RELEASE_IMAGE_NAME
    - docker push $RELEASE_IMAGE_NAME
    - echo Image $IMAGE_NAME taged as latest
